name: goliath_oss
dependencies:
  - anaconda::pandas
  - anaconda::numpy
  - conda-forge::python
  - conda-forge::tqdm
  - pytorch::torch>=2.0.0
  - pytorch::torchvision
  - pytorch3d::pytorch3d
  pip:
    - pillow-avif-plugin
