sid: AXE977
hand_side: left
root_dir: /uca/julieta/oss/goliath/

data:
  root_path: ${root_dir}/m--20230306--0839--AXE977--pilot--ProjectGoliath--Hands--${hand_side}
  shared_assets_path: ${root_dir}/shared/static_assets_hand_${hand_side}.pt
  split: train
  fully_lit_only: True

dataloader:
  batch_size: 4
  num_workers: 8
  shuffle: True

model_name: hand_mvp

model:
  class_name: ca_code.models.${model_name}.AutoEncoder

  n_embs: 64
  image_height: 2048
  image_width: 1334

  cal:
    identity_camera: 400870

  learn_blur: true

summary:
  class_name: ca_code.models.${model_name}.HandMVPSummary

loss:
  class_name: ca_code.loss.ModularLoss
  losses:
    rgb_l2:
      src_key: rgb
      tgt_key: image
      mask_key: segmentation_fgbg
      mask_erode: 3
      weight: 0.0016 # to account for division by 25 in the old code
    vgg:
      src_key: rgb
      tgt_key: image
      mask_key: segmentation_fgbg
      mask_erode: 3
      weight: 1.0
    mask_l1:
      weight: 10.0
      src_key: alpha
      tgt_key: segmentation_fgbg
    learn_blur: 0.001
    alphaprior: 1.0
    primvolsum: 1.0e-4


lr: 5.0e-4
optimizer:
  class_name: torch.optim.AdamW
  per_module:
    poseencoder:
      lr: ${lr}
    geomdecoder:
      lr: ${lr}
    rgbdecoder:
      lr: ${lr}
    cal:
      lr: ${lr}
    learn_blur:
      lr: 0.001

train:
  tag: ${model_name}.${sid}.${hand_side}
  run_dir: runs/${.tag}
  tb_dir: ${.run_dir}/tb
  ckpt_dir: ${.run_dir}/checkpoints

  # CHANGE ME
  n_max_iters: 800_000
  log_every_n_steps: 100
  summary_every_n_steps: 1_000
  ckpt_every_n_steps: 10_000


test_path: /checkpoint/avatar/julietamartinez/goliath/hand_mvp/AXE977/left/1/

test:
  ckpt:
    ckpt_path: ${test_path}/checkpoints/latest.pt
    strict: True
    map_location: cuda:0
  vis_path: ${test_path}/viz
  log_every_n_steps: 1
  data:
    root_path: ${data.root_path}
    shared_assets_path: ${data.shared_assets_path}
    split: test
    fully_lit_only: False
    cameras_subset: [
      "401645",
      "401964",
      "402501",
      "402597",
      "402801",
      "402871",
      "402873",
      "402956",
      "402969",
      "402978",
      "402982",
      "403066",
    ]
    frames_subset: [
      76377,
      76414,
      76439,
      76477,
      76760,
      76807,
      77159,
      77266,
      77384,
      77397,
      77454,
      77920,
    ]
