# by default assuming this is being run in `goliath/`
root_dir: /uca/julieta/oss/goliath/

data:
  root_path: ${root_dir}/s--20230306--1509--AXE977--pilot--ProjectGoliath--ClothedBody--134cams/
  shared_assets_path: ${root_dir}/shared/static_assets_body.pt
  split: train

dataloader:
  batch_size: 4
  num_workers: 8
  shuffle: True

model_name: mesh_vae

model:
  class_name: ca_code.models.${model_name}.AutoEncoder

  encoder:
    n_embs: 1024

  encoder_face:
    n_embs: 256

  decoder:
    init_uv_size: 64
    n_init_channels: 64
    n_min_channels: 4
    n_pose_dims: 98
    n_pose_enc_channels: 16
    n_embs: 1024
    n_embs_enc_channels: 32
    n_face_embs: 256
    uv_size: 1024

  decoder_view:
    net_uv_size: 1024

  upscale_net:
    n_ftrs: 4

  shadow_net:
    uv_size: 2048
    shadow_size: 256
    n_dims: 4

  # pose_to_shadow:
  #   n_pose_dims: 104
  #   uv_size: 2048

  renderer:
    image_height: 2048
    image_width: 1334
    depth_disc_ksize: 3

  cal:
    identity_camera: 400870

  pixel_cal:
    image_height: 2048
    image_width: 1334
    ds_rate: 8

  learn_blur: true

summary:
  class_name: ca_code.models.${model_name}.MeshVAESummary


loss:
  class_name: ca_code.loss.ModularLoss
  losses:
    rgb_l1:
      src_key: rgb
      tgt_key: image
      mask_key: segmentation_fgbg
      mask_erode: 7
      schedule:
        class_name: ca_code.loss.MonotonicWeightSchedule
        start: 0
        end: 10000
        init_value: 1.0
        target_value: 10.0
    effnet:
      src_key: rgb
      tgt_key: image
      mask_key: segmentation_fgbg
      mask_erode: 7
      schedule:
        class_name: ca_code.loss.MonotonicWeightSchedule
        start: 0
        end: 10000
        init_value: 1.0
        target_value: 10.0
    mask_l1:
      schedule:
        class_name: ca_code.loss.MonotonicWeightSchedule
        start: 0
        end: 10000
        init_value: 100.0
        target_value: 50.0
      src_key: alpha
      tgt_key: segmentation_fgbg
    geom_l2:
      schedule:
        class_name: ca_code.loss.MonotonicWeightSchedule
        start: 0
        end: 10000
        init_value: 1.0
        target_value: 1.0e-05
    geom_lap:
      schedule:
        class_name: ca_code.loss.MonotonicWeightSchedule
        start: 0
        end: 10000
        init_value: 100.0
        target_value: 50.0
    head_geom_l2:
      schedule:
        class_name: ca_code.loss.MonotonicWeightSchedule
        start: 0
        end: 10000
        init_value: 0.001
        target_value: 1.0e-05
    head_lap:
      schedule:
        class_name: ca_code.loss.MonotonicWeightSchedule
        start: 0
        end: 10000
        init_value: 100.0
        target_value: 10.0
    # mouth_eyes_lap_penalty: 0.0001
    learn_blur: 0.001
    kl: 0.001
    face_kl: 0.001


lr: 1.0e-4
optimizer:
  class_name: torch.optim.Adam
  per_module:
    encoder:
      lr: ${lr}
    encoder_face:
      lr: ${lr}
    # pose_to_shadow:
    #   lr: ${lr}
    decoder:
      lr: ${lr}
    decoder_view:
      lr: ${lr}
    shadow_net:
      lr: ${lr}
    upscale_net:
      lr: ${lr}
    cal:
      lr: ${lr}
    pixel_cal:
      lr: 0.001
    learn_blur:
      lr: 0.001

train:
  tag: ${model_name}
  run_dir: runs/${.tag}
  tb_dir: ${.run_dir}/tb
  ckpt_dir: ${.run_dir}/checkpoints

  # CHANGE ME
  n_max_iters: 800_000
  log_every_n_steps: 10
  summary_every_n_steps: 10
  ckpt_every_n_steps: 10_000
  clip_grad_norm: 1.0


test_path: /checkpoint/avatar/julietamartinez/goliath/body/AXE977/ClothedBody/1/

test:
  ckpt:
    ckpt_path: ${test_path}/checkpoints/latest.pt
    strict: True
    map_location: cuda:0
  vis_path: ${test_path}/viz
  log_every_n_steps: 1
  data:
    root_path: ${data.root_path}
    shared_assets_path: ${data.shared_assets_path}
    split: test
    fully_lit_only: False
    cameras_subset: [
      "400933",
      "402403",
      "402363",
      "402431",
      "402634",
      "401543",
      "401246",
      "402628",
      "401195",
      "402629",
      "402401",
      "402367",
    ]
    frames_subset: [
      # 13038,
      # 13078,
      # 13298,
      # 13326,
      # 13497,
      # 13628,
      # 13791,
      # 14106,
      # 14299,
      # 14442,
      # 14528,
      # 45818,
      # 46002,
      # 46132,
      # 46165,
      # 46255,
      # 46294,
      # 46463,
      # 46494,
      # 46609,
      # 46750,
      # 46995,
    ]
